=== pjsinco/first-and-third/boards/board.dtd
<!ELEMENT board (play+)>
<!ELEMENT play ((result, conditions*) | fielding*)>
<!ELEMENT result EMPTY>
<!ELEMENT conditions (result)>
<!ELEMENT fielding (result | conditions*)+>

<!ATTLIST conditions 
  zero_outs (t|f) #IMPLIED
  two_outs (t|f) #IMPLIED
  p_sym (w|x|y|z) #IMPLIED
  against (a|b|c|d) #IMPLIED
  infield (c|d) #IMPLIED
  double_cols (t|f) #IMPLIED
  star_14 (t|f) #IMPLIED
  batter_speed (n|f|s) #IMPLIED
  on_1b_speed (n|f|s) #IMPLIED
  on_2b_speed (n|f|s) #IMPLIED
  on_3b_speed (n|f|s) #IMPLIED
  play_it_safe (t|f) #IMPLIED>

<!ATTLIST result 
  state (0|1|2|3|4|5|6|7) #REQUIRED
  batter (to_1b|to_2b|to_3b_|to_home|out|out_at_1b|out_at_2b|out_at_3b|out_at_home|inning_over|atbat) #IMPLIED
  on_1b (hold|to_2b|to_3b|to_home|out_at_1b|out_at_2b|out_at_3b|out_at_home|inning_over) #IMPLIED
  on_2b (hold|to_3b|to_home|out_at_2b|out_at_3b|out_at_home|inning_over) #IMPLIED
  on_3b (hold|to_home|out_at_3b|out_at_home|inning_over) #IMPLIED
  outs (0|1|2|3) #REQUIRED
  runs (0|1|2|3|4) #REQUIRED
  type (atbat|action) #REQUIRED
  des CDATA #REQUIRED
  weird (t|f) #IMPLIED
  charge_ab (t|f|na) #REQUIRED
  event (strikeout|lineout|groundout|flyout|pop_out|sac_fly|forceout|grounded_into_dp|sac_bunt|bunt_groundout|runner_out|single|double|triple|homerun|walk|hit_by_pitch|dropped_third_strike|
    caught_stealing_2b|caught_stealing_3b|caught_stealing_home|stolen_base_2b|stolen_base_3b|stolen_base_home|wild_pitch|
    pitching_substitution|defensive_switch|defensive_substitution|offensive_substitution) #REQUIRED>

<!ATTLIST play 
  val CDATA #REQUIRED>

<!ATTLIST fielding 
  val (1|2|3) #REQUIRED>

<!ATTLIST board 
  state (0|1|2|3|4|5|6|7) #REQUIRED>

=== pjsinco/first-and-third/boards/game-board-5.xml
<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE board SYSTEM "board.dtd">
<board state="5">
  <play val="1">
    <result des="HOMERUN over left field fence" event="HR/F7"/>
  </play>
  <play val="9">
    <result des="SINGLE over short; one runner scores; other to second" event="s"/>
    <conditions two_outs="t">
      <result des="SINGLE over short; one runner scores; other to third" event="S7/L6.3-H;1-3"/>
    </conditions>
  </play>
  <play val="12">
    <fielding val="3">
      <conditions infield="c">
        <result des="Safe at first; F.C.; runner out at home; other to second; A-2B PO-C" event="FC4/G4.3XH(42);1-2"/>
      </conditions>
      <conditions infield="d" zero_outs="t">
        <result des="Double play; A-1B PO-SS A-SS PO-1B; runner on third scores" event="36(1)63/GDP/G3"/>
      </conditions>
      <conditions infield="d" zero_outs="f">
        <result des="Double play; A-1B PO-SS A-SS PO-1B" event="36(1)63/GDP/G3"/>
      </conditions>
      <conditions infield="d" two_outs="t">
        <result des="Groundout; A-1B PO-P" event="31/G3"/>
      </conditions>
    </fielding>
    <fielding val="2">
      <conditions infield="c">
        <result des="Safe at first; F.C.; runner out at home; other to second; A-2B PO-C" event="FC4/G4.3XH(42);1-2"/>
      </conditions>
      <conditions infield="d" zero_outs="t">
        <result des="Double play; A-1B PO-SS A-SS PO-1B; runner on third scores" event="36(1)3/GDP/G3.3-H"/>
      </conditions>
      <conditions infield="d" zero_outs="f">
        <result des="Double play; A-1B PO-SS A-SS PO-1B" event="36(1)3/GDP/G3"/>
      </conditions>
      <conditions infield="d" two_outs="t">
        <result des="Groundout; A-1B PO-P" event="31/G3"/>
      </conditions>
    </fielding>
    <fielding val="1">
      <conditions infield="c">
        <result des="Safe at first; F.C.; runner out at home; other to second; A-2B PO-C" event="FC4/G4.3XH(42);1-2"/>
      </conditions>
      <conditions infield="d" zero_outs="t">
        <result des="Double play; A-2B PO-SS A-SS PO-1B; runner on third scores" event="46(1)3/GCP/G4.3-H"/>
      </conditions>
      <conditions infield="d" zero_outs="f">
        <result des="Double play; A-1B PO-SS A-SS PO-1B" event="36(1)3/GDP/G3"/>
      </conditions>
      <conditions infield="d" two_outs="t">
        <result des="Groundout; A-1B PO-P" event="31/G3"/>
      </conditions>
    </fielding>
  </play>
  <play val="21">
    <fielding val="3">
      <conditions two_outs="t">
        <result des="Strikeout; catcher drops third strike; one runner scores; other to second; batter to first; passed ball" event="K+PB.3-H;1-2;B-1"/>
      </conditions>
      <result des="Strikeout; PO-C" event="K"/>
    </fielding>
    <fielding val="2">
      <conditions two_outs="t">
        <result des="Strikeout; catcher drops third strike; batter safe at first, filling the bases; passed ball" event="K+PB;1-2;B-1"/>
      </conditions>
      <result des="Strikeout; PO-C" event="K"/>
    </fielding>
    <fielding val="1">
      <result des="Ball; catcher throws wild to third; one runner scores; other to second; E-C" pitch="B" event="PO3(E2/TH).3-H(NR)(UR)"/>
    </fielding>
  </play>
  <play val="29">
    <fielding val="3">
      <result des="Out at first; runner to second; other holds; A-P PO-1B" event="13/G1.1-2"/>
      <conditions p_sym="x">
        <result des="Strikeout; PO-C" event="K"/>
      </conditions>
    </fielding>
    <fielding val="2">
      <result des="Out at first; runner to second; other holds; A-P PO-1B" event="13/G1.1-2"/>
      <conditions p_sym="x">
        <result des="Strikeout; PO-C" event="K"/>
      </conditions>
    </fielding>
    <fielding val="1">
      <result des="Out at first; runner to second; other holds; A-P PO-1B" event="13/G1.1-2"/>
      <conditions p_sym="x">
        <result des="Strikeout; PO-C" event="K"/>
      </conditions>
    </fielding>
  </play>
  <play val="37">
    <fielding val="3">
      <conditions on_1b_speed="s">
        <result des="Runner on first holds" pitch="K" event=".1-1"/>
      </conditions>
      <result des="Runner on first steals second; other holds third" event="SB2.3-3"/>
    </fielding>
    <fielding val="2">
      <conditions two_outs="t">
        <result des="Runner on first out stealing 2nd; A-C PO-SS" event="CS2(26)"/>
      </conditions>
      <result des="Runner on first out stealing 2nd; A-C PO-SS; other scores" event="CS2(26)"/>
    </fielding>
    <fielding val="1">
      <conditions two_outs="t">
        <result des="Runner on first out stealing 2nd; A-C PO-SS" event="CS2(26)"/>
      </conditions>
      <result des="Runner on first out stealing 2nd; A-C PO-SS; other holds" event="CS2(26)"/>
    </fielding>
  </play>
</board>
